import {
  Search,
  BarChart3,
  Network,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  X,
  Menu,
  Gauge,
  LineChart,
  LayoutGrid,
  Shield,
  MapPin,
  Coins,
  AlertTriangle,
  Brain,
  Grid3X3,
  TrendingUp,
  Instagram,
  Twitter,
  Facebook,
  Linkedin,
} from "lucide-react";

export const Icons = {
  search: Search,
  barChart: BarChart3,
  network: Network,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  close: X,
  menu: Menu,
  gauge: Gauge,
  lineChart: LineChart,
  layoutGrid: LayoutGrid,
  shield: Shield,
  mapPin: MapPin,
  coins: Coins,
  alertTriangle: AlertTriangle,
  brain: Brain,
  apPin: MapPin,
  grid3X3: Grid3X3,
  trendingUp: TrendingUp,
} as const;

export type IconName = keyof typeof Icons;
